esphome:
  name: lili
  friendly_name: lili

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
  logs:
    component: ERROR

external_components:
  # use all components from a local folder
  #- source:
  #    type: local
  #    path: my_components
  - source: github://cjszz2001/mmwave-kit-external-components@main
    refresh: 0s

# Enable Home Assistant API
api:
  encryption:
    key: "thlmovTSnSxO4dzmW+ZACRqQBiOGZEIbH+pUGNw9LMY="

ota:
  password: "750a2d7472b611b18d8660f379932381"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lili Fallback Hotspot"
    password: "uxl1utdfmTye"

captive_portal:
uart:
  id: uart_bus
  baud_rate: 115200
  #baud_rate: 1250000
  rx_pin: 4
  tx_pin: 5
  parity: NONE
  stop_bits: 1

ti6432:
  id: my_ti6432


sensor:
  - platform: ti6432
#    custom_presence_of_detection:
#      name: "Z1 presence"
#    movement_signs:
#      name: "Z2 presence"
#    custom_motion_distance:
#      name: "Z3 presence"
    custom_spatial_static_value:
      name: "Target ID"
    custom_spatial_motion_value:
      name: "Human Probability"
    custom_motion_speed:
      name: "Human Count"
    custom_mode_num:
      name: "Human Prob in 317 (index 0)"
      filters:
        - filter_out: 0.5
        - clamp:
            min_value: 0
            max_value: 1
            ignore_out_of_range: true
        - sliding_window_moving_average:
            window_size: 5
                  